### PR TITLE
Use alembic multiple directories for revision tracking

### PR DESCRIPTION
**Pull request by nZac**

### CODE REVIEW

**Comment by 3noch** [comment]
I'd still like to do this, but it need to understand it better, especially in light of the fact that KegBouncer needs to allow the app to parameterize its migrations for the User entity.

**Comment by nZac** [comment]
What don't you understand? I can try and help explain what is happening.  Also, [the alembic docs on branching](http://alembic.readthedocs.org/en/latest/branches.html) are very helpful.

**Comment by 3noch** [comment]
"Lack of understanding because I have not tried yet" ≠ "Failure to understand after trying" :wink:

**Comment by 3noch** [comment]
Merged.

**Pull request closed without merging**
